// <auto-generated />
using System;
using FoiaProcessor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoiaProcessor.Data.Migrations
{
    [DbContext(typeof(FoiaDbContext))]
    partial class FoiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoiaProcessor.Data.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FoiaRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("RelatedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FoiaRequestId", "Timestamp");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FoiaRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedactedContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedactionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IncludeInRelease")
                        .HasColumnType("bit");

                    b.Property<string>("SourceDocumentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceUri")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FoiaRequestId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.FoiaRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("RequestedEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RequestedStartDate")
                        .HasColumnType("date");

                    b.Property<string>("RequestorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("RequestorFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequestorMailingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestorOrganization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequestorPhone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("FoiaRequests");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.Redaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("DetectionSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EndOffset")
                        .HasColumnType("int");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("PiiType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacementText")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool?>("ReviewerApproved")
                        .HasColumnType("bit");

                    b.Property<string>("ReviewerComments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("StartOffset")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Redactions");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.ReleasePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FoiaRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SasExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SasUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ZipBlobName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("FoiaRequestId")
                        .IsUnique();

                    b.ToTable("ReleasePackages");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.ReviewTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedReviewer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FoiaRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewerComments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewerDecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoiaRequestId");

                    b.ToTable("ReviewTasks");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.AuditEvent", b =>
                {
                    b.HasOne("FoiaProcessor.Data.Entities.FoiaRequest", "FoiaRequest")
                        .WithMany("AuditEvents")
                        .HasForeignKey("FoiaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoiaRequest");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.Document", b =>
                {
                    b.HasOne("FoiaProcessor.Data.Entities.FoiaRequest", "FoiaRequest")
                        .WithMany("Documents")
                        .HasForeignKey("FoiaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoiaRequest");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.Redaction", b =>
                {
                    b.HasOne("FoiaProcessor.Data.Entities.Document", "Document")
                        .WithMany("Redactions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.ReleasePackage", b =>
                {
                    b.HasOne("FoiaProcessor.Data.Entities.FoiaRequest", "FoiaRequest")
                        .WithOne("ReleasePackage")
                        .HasForeignKey("FoiaProcessor.Data.Entities.ReleasePackage", "FoiaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoiaRequest");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.ReviewTask", b =>
                {
                    b.HasOne("FoiaProcessor.Data.Entities.FoiaRequest", "FoiaRequest")
                        .WithMany("ReviewTasks")
                        .HasForeignKey("FoiaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoiaRequest");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.Document", b =>
                {
                    b.Navigation("Redactions");
                });

            modelBuilder.Entity("FoiaProcessor.Data.Entities.FoiaRequest", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("Documents");

                    b.Navigation("ReleasePackage");

                    b.Navigation("ReviewTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
